# Generated by Django 2.1.4 on 2019-06-02 15:31

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [("artists", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="song",
            name="recording_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2019, 6, 2, 15, 30, 56, 238024, tzinfo=utc),
                verbose_name="Recording Time",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="song",
            name="release_date",
            field=models.DateField(
                default=datetime.date(2019, 6, 2),
                verbose_name="Release Date"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="song",
            name="release_time",
            field=models.TimeField(
                default=datetime.time(15, 31, 26, 19287),
                verbose_name="Release Time"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="song",
            name="song_type",
            field=models.CharField(
                choices=[("1", "Single"), ("2", "Collaboration"), ("3",
                                                                   "Skit")],
                default="1",
                max_length=1,
                verbose_name="Type",
            ),
        ),
    ]
